# Generated by Django 5.1.3 on 2024-12-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user_invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('activate_invite_code', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
