# Generated by Django 5.1.3 on 2024-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
